env:
  commonjs: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  space-before-function-paren: off
  generator-star-spacing: off
overrides:
  - files:
      - '*.test.js'
      - 'jest-test-setup.js'
    rules:
      'no-undef': 'off'
