extends:
  - '@exsoinn/eslint-config-exsoinn'
overrides:
  - files:
    - "jest-test-setup.js"
    env:
      jest: true
  - files:
      - "*.ts"
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
      'no-use-before-define': off
      '@typescript-eslint/no-require-imports': off
      '@typescript-eslint/no-empty-object-type': off
