branches: ['main']
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - - '@semantic-release/github'
    - assets:
      - path: 'CHANGELOG.md'
        label: 'Summary of changes'
      - path: 'package.json'
        label: 'NPM package.json'
      - path: 'package-lock.json'
        label: 'NPM package-lock.json'
